### ISSUE TITLE
Firebase 3.0.0

### ISSUE THREAD

**Issue by navmalc** [PBRT/reactogo#7]
I notice that the firebase reference is still 2.3.2 - any thought to updating with 3 series firebase?

**Comment by PBRT** [comment]
I will update it for supporting the Firebase 3.0.0 auth API. If you want to do me a PR I'll be more than happy to merge it ;)

**Comment by PBRT** [comment]
Firebase 3.0.0. now supported as part of : https://github.com/PBRT/reactogo/commit/ab6463f65777c323ed1719f3b432c42d165d462e

Closing the issue
